# -*- coding: utf-8 -*-
"""exAIminer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K2PYdSmOIebTIUrARdEGRM30WfmNXcNI
"""

class MathQuestionApp:
    def __init__(self):
        self.questions = [
            {"question": "2 + 2", "answer": 4, "explanation": "The sum of 2 and 2 is 4."},
            {"question": "5 - 3", "answer": 2, "explanation": "Subtracting 3 from 5 gives the result 2."},
            {"question": "4 * 6", "answer": 24, "explanation": "Multiplying 4 by 6 results in 24."},
            {"question": "10 / 2", "answer": 5, "explanation": "Dividing 10 by 2 equals 5."},
        ]
        self.learning_resource = "[Book Name ABC, Page #44] This will help you better understand why this is true."

    def ask_questions(self):
        for i, q in enumerate(self.questions, start=1):
            user_answer = input(f"{i}. What is {q['question']}? Enter your answer: ")
            try:
                user_answer = float(user_answer)
                if user_answer == q['answer']:
                    print("Correct! Good job.")
                else:
                    print(f"Oops! That's incorrect. {q['explanation']} You might want to read '{self.learning_resource}' to improve.")
            except ValueError:
                print("Invalid input. Please enter a valid number.")

    def run(self):
        print("Welcome to the Math Question App!")

        self.ask_questions()

        print("Thanks for using the Math Question App. Goodbye!")


if __name__ == "__main__":
    math_app = MathQuestionApp()
    math_app.run()